# Generated by Django 4.2.3 on 2023-10-25 06:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("App01", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="WebcamSnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="webcam_snapshots/")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
