# Generated by Django 4.2.3 on 2023-10-25 06:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("App01", "0002_webcamsnapshot"),
    ]

    operations = [
        migrations.AddField(
            model_name="webcamsnapshot",
            name="video",
            field=models.FileField(
                blank=True, null=True, upload_to="webcam_snapshots/videos/"
            ),
        ),
        migrations.AlterField(
            model_name="webcamsnapshot",
            name="image",
            field=models.ImageField(upload_to="webcam_snapshots/images/"),
        ),
    ]
