# Generated by Django 4.2.3 on 2023-10-25 13:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("App01", "0004_remove_webcamsnapshot_video_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="WebcamVideo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("video", models.FileField(upload_to="webcam_videos/")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name="WebcamSnapshot",
        ),
    ]
